- hosts: web_servers
  become: true  
  tasks:
    - name: Create Docker network named monitoring-network
      docker_network:
        name: monitoring-network
        driver: bridge

    - name: Copy Promtail config
      copy:
        content: |
          server:
            http_listen_port: 9080
            grpc_listen_port: 0

          clients:
            - url: http://loki:3100/loki/api/v1/push

          positions:
            filename: /tmp/positions.yaml

          scrape_configs:
            - job_name: system
              static_configs:
                - targets:
                    - localhost
                  labels:
                    job: varlogs
                    __path__: /var/log/*.log
        dest: ./promtail-config.yml

    - name: Copy Loki config
      copy:
        content: |
          server:
            http_listen_port: 9080
            grpc_listen_port: 0

          positions:
            filename: /tmp/positions.yaml

          clients:
            - url: http://loki:3100/loki/api/v1/push

          scrape_configs:
            - job_name: system
              static_configs:
                - targets:
                    - localhost
                  labels:
                    job: varlogs
                    __path__: /var/log/*log

            - job_name: docker
              static_configs:
                - targets:
                    - localhost
                  labels:
                    job: docker_logs
                    __path__: /var/lib/docker/containers/*/*-json.log
        dest: ./loki-config.yaml

    - name: Copy Prometheus config
      copy:
        content: |
          global:
            scrape_interval: 15s

          scrape_configs:
            - job_name: 'prometheus'
              metrics_path: "/prometheus/metrics"
              static_configs:
                - targets: ['prometheus:9090']

            - job_name: 'grafana'
              static_configs:
                - targets: ['grafana:3000']

            - job_name: 'cadvisor'
              static_configs:
                - targets: ['cadvisor:8080']

            - job_name: 'loki'
              static_configs:
                - targets: ['loki:3100']
        dest: ./prometheus.yml
