name: Terraform Plan with Cost Estimation

on:
  pull_request:
    branches:
      - infra_main

jobs:
  terraform-plan:
    name: Generate Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

      - name: Initialize Terraform
        run: terraform init

      - name: Generate Terraform Plan
        run: terraform plan -out=tfplan

      - name: Show Terraform Plan
        run: terraform show -no-color tfplan

      - name: Install InfraCost CLI
        run: |
          curl -sSL https://github.com/infracost/infracost/releases/latest/download/infracost-linux-amd64.tar.gz | tar xz
          mv infracost-linux-amd64 /usr/local/bin/infracost

      - name: Generate Cost Estimate
        run: |
          infracost breakdown --path . \
          --show-skipped --format table

      - name: Post Plan to PR
        uses: marocchino/sticky-pull-request-comment@v3
        with:
          path: tfplan
