name: Infra Features Pipeline

on:
  pull_request:
    branches:
      - infra_main

permissions:
  pull-requests: write 
  contents: read      

jobs:
  terraform:
    name: Run Terraform Steps
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6  

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        id: plan
        run: terraform plan -out=tfplan && terraform show -json tfplan > tfplan.json

      - name: Post Terraform Plan to PR
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2.6.1
        with:
          header: Terraform Plan
          message: |
            ```json
            $(cat tfplan.json)
            ```
