name: Terraform Plan with Cost Estimation

on:
  pull_request:
    branches:
      - infra_main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "us-east-1"

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Terraform Init
        run: terraform init

      - name: Generate Terraform Plan
        run: terraform plan -out=tfplan

      - name: Show Terraform Plan Output
        run: terraform show -json tfplan > tfplan.json

      - name: Install InfraCost
        run: |
          curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH # Add infracost to PATH

      - name: Run InfraCost
        run: infracost breakdown --path=tfplan.json --format=json > infracost.json

      - name: Comment on PR with Terraform Plan and Cost Estimation
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: "Terraform Plan and Cost Estimation"
          message: |
            ## Terraform Plan:
            ```hcl
            $(terraform show tfplan)
            ```

            ## Cost Estimation:
            $(infracost output --path infracost.json --format table)
